# ===============================
# DATABASE - NEON POSTGRESQL
# ===============================

db.url=jdbc:postgresql://ep-broad-sound-ahelbw81-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
db.username=neondb_owner
db.password=npg_zn7ZGwKhx8ek
db.driver=org.postgresql.Driver

# ===============================
# HikariCP Configuration (Neon)
# ===============================
db.pool.size=5
db.pool.timeout=30000

